### ISSUE TITLE
`compFilter` not working as expected

### ISSUE THREAD

**Issue by Peque** [ubalance-team/magum#1]
Function `compFilter` is not working as expected, it seems. Have you tested it?

There is at least one thing that seems wrong:

``` python
aux = 0
# Some more code here
if aux == 0:
    # We set angles based on accelerometer data
else:
    # We never get here...
```

So basically I think angles are calculated only with the accelerometer and, therefore, rotations over the _z_ axis are not detected (supposing calibration of the board and rotation over a flat surface).

**Comment by orla11** [comment]
It seems you're right, thank you for opened the issue, we'll fix it as soon as possible.

**Comment by cucio92** [comment]
The problem is not resolved yet. We are fixing it

**Comment by cucio92** [comment]
Now the Complementary Filter should work. Unfortunately we can not test it. If you can do it, please let us know if it works. Thanks

**Comment by Peque** [comment]
Thanks for your fast response. :blush:

Sadly I do not have an Udoo anymore. I was just working this weekend in a hackathon with it. So I will not be able to try the new changes.

However, we made a software for real-time visualization of gyroscope and accelerometer data. [Here you can find a video of this tool](https://www.youtube.com/watch?v=Myoru4sZerA).

Here is the code in case you want to try it:
- Server: https://github.com/Hackathon-Sanjurjo/UdooData
- Client: https://github.com/Hackathon-Sanjurjo/sensor-gui

The projects are not well documented at the moment, but I will be happy to help you configure them if you need to (your feedback on difficulties setting it up will be useful to create better README files).

The server part is to be put in the Udoo. It uses ZeroMQ to publish real-time data over the network. This means you can connect any number of clients, at any time, to this data stream and start visualizing or processing the real-time data. Also, ZeroMQ handles disconnections, so there is no problem with interrupting the server and starting it again with some changes; the client will continue receiving the new data once the server starts publishing again.

**Comment by cucio92** [comment]
Ok. Thanks!

**Comment by Peque** [comment]
By the way, if you finally find some time to try it out, even if you do not have any problems running/configuring the tool, do not hesitate to tell us your opinion or suggestions on how to improve it! :wink:

**Comment by orla11** [comment]
Your work is awsome! Congratulations, we'll dive into it!
